### ISSUE TITLE
Improve MetalLB to use service's annotation for target judgment

### ISSUE THREAD

**Issue by seroron** [google/metallb#405] opened 2019-02-23 02:01 UTC
**Is this a bug report or a feature request?**:
feature request

**What happened**:
I want to use layer 2 mode at multiple subnet environments.

**What you expected to happen**:
Improve MetalLB to use service's annotation for target judgment.

**How to reproduce it (as minimally and precisely as possible)**:
By use multiple MatalLB sets, supports multiple subnet environments. 
It also resolves #389.

ex)
* subnetA
```
containers:
  - name: speaker
     image: metallb/speaker:master
     args:
        - --port=7472
        - --config=config
        - --metallb.class=my_subnet_a   <-- add
nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
    - matchFields:
      - key: failure-domain.beta.kubernetes.io/zone
        operator: In
        values:
        - my_subnet_a
```
```
kind: Service
metadata:
  name: appA
  annotations:
    service.beta.kubernetes.io/metallb.class: my_subnet_a  <-- add
 spec:
  type: LoadBalancer
```

* subnetB
```
containers:
- name: speaker
   image: metallb/speaker:master
   args:
      - --port=7472
      - --config=config
      - --metallb.class=my_subnet_b   <-- add
nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
    - matchFields:
      - key: failure-domain.beta.kubernetes.io/zone
        operator: In
        values:
        - my_subnet_b
```
```
kind: Service
metadata:
  name: appB
  annotations:
    service.beta.kubernetes.io/metallb.class: my_subnet_b  <-- add
 spec:
  type: LoadBalancer
```

**Anything else we need to know?**:
This is same concept for NGINX Ingress Controller's '--ingress-class'
https://kubernetes.github.io/ingress-nginx/user-guide/cli-arguments/

**Environment**:
- MetalLB version: 0.7.3
- Kubernetes version: 1.13

**Comment by Ultrafenrir** [comment] 2019-02-28 07:56
+1

**Comment by danderson** [comment] 2019-02-28 23:21
Thanks for filing. You're proposing a solution rather than describing a problem, so I'm not sure what you're trying to solve. The solution as described adds a lot of complexity to both MetalLB and configurations users have to deploy, so I'm not super excited about it.

Can you describe the problem you're trying to solve? What configuration (set of LB IPs, backends, etc.) are you trying to achieve that MetalLB currently cannot?

**Comment by alexlovelltroy** [comment] 2019-03-01 02:53
I think you're looking for the Service annotation `metallb.universe.tf/address-pool:` 

if you name the address pools in the configmap, you can reference them in the Service definition.

There's more detail in the docs under [requesting specific ips](https://github.com/google/metallb/blob/c0538f39bfab469dd0ef99708ecda7e77fcc66f5/website/content/usage/_index.md#requesting-specific-ips)

**Comment by seroron** [comment] 2019-03-02 00:29
@danderson
Thank you for your response.
My k8s cluster is made up of multiple subnets.
 -> 10.100.10.0/24, 10.200.11.0/24, ….
I want to use MetalLB by layer 2 mode.
I do not have permission to operate the router, so I can not use BGP mode.

@alexlovelltroy
Thank you for your suggestion.
I  am using a currently ```metallb.universe.tf/address-pool:```.
It is going well,
```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: subnet_A_pool
      protocol: layer2
      addresses:
      - 10.100.10.100-10.100.10.200
    - name: subnet_B_pool
      protocol: layer2
      addresses:
      - 10.200.11.100-10.200.11.200
```
```
kind: Service
metadata:
  name: app_subnet_A
  annotations:
    metallb.universe.tf/address-pool: subnet_A_pool
 spec:
   type: LoadBalancer
   selector:
      app: app_subnet_A
```
```
kind: Service
metadata:
  name: app_subnet_B
  annotations:
    metallb.universe.tf/address-pool: subnet_B_pool
 spec:
   type: LoadBalancer
   selector:
      app: app_subnet_B
```

Note: 
It must be separate services per subnet.
When service’s targets are pods exists at multiple subnet, the leader node which exists different subnet to VIP may be selected.
In this situation. this node can not receive ARP.



@danderson
Currently in L2 mode, only nodes with a local pod are eligible to become the announcer for a service. 
So this method is successful.
But I afraid that it become fail in future releases even in situations which pods exists only one subnet.
It will fail if MetalLB select a leader node on a different subnet from the VIP.
#359
> In a future release, when the service is in Cluster mode, MetalLB will prefer nodes with local pods if possible, but if not possible it'll still allow using any other node.

**Comment by danderson** [comment] 2019-03-16 04:33
What you're trying to do is poorly supported by MetalLB, because it's poorly supported by the underlying network protocol (ARP). These kinds of network topologies will only ever work right if you use L3-aware network protocols like BGP or OSPF, trying to use L2 protocols will always have weird broken edge cases.

If you use the Local `externalTrafficPolicy` and the subnet-per-pool strategy that Alex described, combined with nodeSelectors to pin your pods to the correct subnets, that's the closest you can get to making this work. I don't think MetalLB can change to make this use case work better, it'll just add more complexity to work around the fundamental problem of trying to do L3 routing with L2 protocols, which is impossible.

**Comment by danderson** [comment] 2019-03-16 04:34
Duplicate of #389

**Closed by danderson** 2019-03-16 04:34 UTC
Labels: enhancement, need-more-info
