### ISSUE TITLE
Get layer2 addresses from DHCP, not hardcoded array

### ISSUE THREAD

**Issue by marwooj** [google/metallb#267] opened 2018-06-25 12:58 UTC
**Is this a bug report or a feature request?**: feature request

**What happened**: I just wonder if it is possible to assign IP addresses from DHCP, rather than hardcoded array?

**What you expected to happen**: I would love to have possibility to use config like this:
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: my-ip-space
      protocol: layer2
      addresses:
      - DHCP

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- MetalLB version:
- Kubernetes version:
- BGP router type/version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):

**Comment by danderson** [comment] 2018-06-27 15:49
Thanks for the report! This is not currently possible, but it's something we might do in the future, and it's tracked in #157 .

Duplicate of #157

**Closed by danderson** 2018-06-27 15:49 UTC
