### ISSUE TITLE
Pod/deployment not accessible after restart/redeploy unless assigned new IP

### ISSUE THREAD

**Issue by paulmorabito** [google/metallb#412] opened 2019-03-05 02:15 UTC
Hi,

I am finding an issue whereby when I create an external IP for a pod/deployment everything works fine (i.e. the pod is accessible at the designated IP) until the pod/deployment is restarted or redeployed. When that occurs, even if I remove the load balancing service and re-add it, the pod/deployment is never accessible again on that IP. To make it re-accessible, I need to delete the existing load balancing service and re-add with a new IP address.

Kubernetes versions:
--
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
--

The cluster was built using RKE and I'm using Rancher 2.1.6.

Example load balancer service file (I have another for UDP ports)

--
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  labels:
    app: pihole
  name: pihole-tcp
  namespace: services
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.1.243
  ports:
  - name: pihole-http
    port: 80
    protocol: TCP
    targetPort: pihole-http
  - name: pihole-https
    port: 443
    protocol: TCP
    targetPort: pihole-https
  - name: dns
    port: 53
    protocol: TCP
    targetPort: dns
  selector:
    app: pihole
  sessionAffinity: None
  type: LoadBalancer
--

Upon deployment, if I look at the logs of speaker, I can see:

--
{"caller":"main.go:229","event":"serviceAnnounced","ip":"192.168.1.243","msg":"service has IP, announcing","pool":"my-ip-space","protocol":"layer2","service":"services/pihole-tcp","ts":"2019-03-04T07:50:23.299506509Z"}
{"caller":"main.go:229","event":"serviceAnnounced","ip":"192.168.1.243","msg":"service has IP, announcing","pool":"my-ip-space","protocol":"layer2","service":"services/pihole-udp","ts":"2019-03-04T07:51:19.490922313Z"}
--

If I do a "sudo iptables-save|grep "192.168.1.243" I get
--
-A KUBE-SERVICES -d 192.168.1.243/32 -p tcp -m comment --comment "services/pihole-tcp:dns loadbalancer IP" -m tcp --dport 53 -j KUBE-FW-HXHB5LEISI5O27LN
-A KUBE-SERVICES -d 192.168.1.243/32 -p udp -m comment --comment "services/pihole-udp:dns-udp loadbalancer IP" -m udp --dport 53 -j KUBE-FW-54HQV7VQ4SMSCLJJ
-A KUBE-SERVICES -d 192.168.1.243/32 -p tcp -m comment --comment "services/pihole-tcp:pihole-http loadbalancer IP" -m tcp --dport 80 -j KUBE-FW-ENXAJ3CLTIX7QU5O
-A KUBE-SERVICES -d 192.168.1.243/32 -p udp -m comment --comment "services/pihole-udp:client-udp loadbalancer IP" -m udp --dport 67 -j KUBE-FW-WRZCHMT2Y2OXKLOK
--

Everything seems to be working and does on the first allocation of the IP to the pod/deployment but again, as I said above, if that pod is restarted/redeployed, it is never again accessible (even if I remove and re-add the load balancer services).

Any ideas would be very appreciated!

**Comment by samvdb** [comment] 2019-03-14 19:12
Use the master branch of the speaker pod. See danderson his comment: https://github.com/google/metallb/issues/399#issuecomment-468481117

#399 

In helm:

```yaml
speaker:
  image:
    repository: metallb/speaker
    tag: master
```

**Comment by danderson** [comment] 2019-03-16 04:25
Duplicate of #399

**Closed by danderson** 2019-03-16 04:25 UTC
