### ISSUE TITLE
External (public) IP not reachable in TCP from other nodes of cluster

### ISSUE THREAD

**Issue by protheusfr** [google/metallb#400] opened 2019-02-13 14:32 UTC
**Is this a bug report or a feature request?**:
Seems to be a bug (or a human error...)

**What happened**:
I've start a bare metal cluster with only one node (master without toleration in order to deploy workload on it).
Some of my workload is exposed to Internet either through Ingress + LoadBalancer or directly via LoadBalancer.
Booth getting his public IP from Metallb in ARP mode.
Everything working fine.

Now I've to add a second node, he joined the cluster without issue and speaker's logs looks good.

Despite that, from this second node, I can ping any of external IP of master node but I **can't** connect to any service hosted on them via TCP (and by the way HTTP).

With a tcpdump on public interface, I can see ICMP packet during a ping but nothing with a curl on the same target.

**What you expected to happen**:

Can reach all node public IP from all node of the cluster.

**How to reproduce it (as minimally and precisely as possible)**:
Build a small cluster with exposed workload on master node, try to reach them on public IP from other nodes.

**Anything else we need to know?**:
nop

**Environment**:
- MetalLB version: metallb/controller:v0.7.3 
- Kubernetes version: v1.13.3
- BGP router type/version: - 
- OS (e.g. from /etc/os-release): 
```
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`): `Linux lm04 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by protheusfr** [comment] 2019-02-13 19:10
Update, this occur only for services with `externalTrafficPolicy: Local`, usefull for withe/black list some source IP on Ingress.
So my question is : have we a way to instruct metallb to NOT load iptable rules that attract traffic for `externalTrafficPolicy: Local` service when pod aren't on local node ?

**Comment by danderson** [comment] 2019-02-13 19:37
This is a KI of Kubernetes: depending on the network addon and k8s version, connecting to LB services from cluster nodes does not work. I think this is a duplicate of https://github.com/google/metallb/issues/258 , can you confirm?

**Comment by protheusfr** [comment] 2019-02-13 20:09
Not sure, in my case I use Weave and clearly it's related on how Metallb build iptable rules.
The same iptable rules are deployed on all node despite with an `externalTrafficPolicy: Local` only the node that own the LoadBalancer IP and the concerned pods can process the traffic. 
Then on the other nodes, MetalLb must not deploy rules to process traffic that target this LoadBalancer IP.

**Comment by danderson** [comment] 2019-02-28 23:25
MetalLB doesn't build any iptables rules. All the packet routing functionality is provided by kube-proxy and the network addon, MetalLB has nothing to do with it.

Weave has known issues with routing to LB services from the nodes, so I think this is indeed a duplicate. Unfortunately there's nothing I can do about this, MetalLB's only responsibility is to get packets to the nodes, and from there kube-proxy and the network addon are responsible for getting them to the right place.

**Closed by danderson** 2019-02-28 23:25 UTC

**Comment by BumwooPark** [comment] 2019-03-12 14:20
> MetalLB doesn't build any iptables rules. All the packet routing functionality is provided by kube-proxy and the network addon, MetalLB has nothing to do with it.
> 
> Weave has known issues with routing to LB services from the nodes, so I think this is indeed a duplicate. Unfortunately there's nothing I can do about this, MetalLB's only responsibility is to get packets to the nodes, and from there kube-proxy and the network addon are responsible for getting them to the right place.

i have same issue can i get infomation or link about `Weave has known issues with routing to LB services from the nodes`

**Comment by johnmarcou** [comment] 2019-06-07 01:37
Just got the same side-effect. Unable to contact a LoadBalancer IP from the masters of the cluster.

The reason was the service was using `externalTrafficPolicy: Local`. So the master node comes back to itself to find the "local" pod of the service (an ingress controller), which doesn't exist since no schedule are allowed on this guys.

I first thought it was a bug in MetalLB, which is not. I would say it's only a misconfiguration.
A `externalTrafficPolicy: Cluster` service, or a toleration on the ingress to spin a pod on the master, would fix the issue
